export type Language = 'en' | 'zh'

export const COPY_BY_LANGUAGE = {
  en: {
    appTitle: 'Dayan Ritual',
    appKicker: 'Guantian',
    appSubtitle: 'Reading Change Through the I Ching',
    languageToggle: '漢',
    smallScreen: 'A larger screen is recommended',
    questionLabel: 'What is being asked',
    questionPlaceholder: 'Place the question on the table',
    beginButton: 'Begin',
    authEnterWithEmail: 'Enter',
    authLocalBypass: 'Enter locally',
    authEmailPlaceholder: 'email',
    authSendLink: 'Send quiet link',
    authCheckMail: 'A link has been sent. Return here after opening it.',
    authRequired: 'Enter first. The gua should know who is asking.',
    authError: 'The entrance did not open. Try once more.',
    authErrorPrefix: 'Supabase says',
    authSignedIn: 'Entered as',
    authTemporaryAccount: 'Temporary account',
    authTemporaryHint: 'This browser keeps your readings. Bind email later to recover them elsewhere.',
    authLeave: 'Leave',
    account: 'Account',
    dailyAlreadyCast: "Today's gua has already been cast.\nToo many casts scatter the question. Let it sit, and return with one clear mind tomorrow.",
    dailyCheckFailed: 'The day could not be checked. Wait a moment and try again.',
    testComplete: 'Test gua',
    modePaused: '3D paused',
    insightButton: 'This gua reflects',
    resetButton: 'Return',
    observing: 'Reading the gua',
    hexagramComplete: 'The gua is formed',
    expandChanges: 'Show eighteen changes',
    collapseChanges: 'Hide eighteen changes',
    recordsTitle: 'Notes',
    currentPrefix: 'Now',
    linePrefix: 'Line',
    changePrefix: 'Change',
    noLineYet: 'No line has settled',
    currentLineInProgress: 'Line in progress',
    resultQuestion: 'Asked',
    primaryGua: 'Primary gua',
    changedGua: 'Changed gua',
    movingLines: 'Moving lines',
    sourceTaken: 'Texts taken',
    mainText: 'Main text',
    supportText: 'Supporting text',
    originalGua: 'Primary gua',
    transformedGua: 'Changed gua',
    home: 'Return home',
    book: 'Read the old note',
    historyTitle: 'Recent notes',
    historyKicker: 'Kept here',
    historyEmpty: 'No completed reading has been kept here yet.',
    historyClose: 'Close history',
    historyNotePlaceholder: 'Add a quiet note',
    splitChoiceHint: 'You divide the stalks here; the result comes from your choice.',
    aboutTitle: 'About Guantian',
    aboutClose: 'Close about Guantian',
    shareButton: 'Share this reading',
    shareWriting: 'Writing the hexagram...',
    sharePosterTitle: 'Hexagram note',
    sharePreviewTitle: 'The note is ready',
    shareSave: 'Save PNG',
    shareSaveHint: 'On mobile, open or long-press the image to keep it.',
    supportLine: 'If this reading held something for you, you can leave a cup of tea.',
    supportButton: 'Leave a cup of tea',
    returnTomorrow: 'This is today’s question. Return tomorrow for another.',
    onboardingPages: [
      'Dayan Ritual is one of the oldest ways of forming a gua in the I Ching.',
      'The old view was simple: change leaves a shape behind.',
      'Fifty yarrow stalks. One returns to heaven. Forty-nine enter change.',
      'Divide into two. Heaven and earth. Take one. Count by fours.',
      'You are not predicting the future. You are watching where this moment of change is turning.',
    ],
    yinLine: 'yin line',
    yangLine: 'yang line',
    noMovingLine: 'None',
    changingLine: 'changing',
    unchangedLine: 'unchanged',
    status: {
      idle: 'Awaiting the question',
      awaitingQuestion: 'The question is placed before the table',
      reserveOne: 'Fifty stalks; forty-nine are used',
      chooseSplit: 'Choose where the stalks divide',
      split: 'Dividing into two',
      takeOne: 'One is taken from the right',
      countLeft: 'Counting the left pile by fours',
      countRight: 'Counting the right pile by fours',
      changeComplete: 'One change is complete',
      lineComplete: 'Three changes settle into one line',
      hexagramComplete: 'The gua is formed',
      waitingSplitDetail: 'Click anywhere on the stalk bundle to divide it',
    },
    detail: {
      left: 'left',
      right: 'right',
      takeOne: 'right takes one',
      leftRemainder: 'left remains',
      rightRemainder: 'right remains',
      removed: 'removed',
      remaining: 'left',
    },
    lineValues: {
      6: 'old yin',
      7: 'young yang',
      8: 'young yin',
      9: 'old yang',
    },
  },
  zh: {
    appTitle: '大衍筮法',
    appKicker: '观天',
    appSubtitle: '以《易经》观变化',
    languageToggle: 'En',
    smallScreen: '建议使用较大屏幕体验',
    questionLabel: '所问何事',
    questionPlaceholder: '将问题留在案前',
    beginButton: '起筮',
    authEnterWithEmail: '入内',
    authLocalBypass: '本地入内',
    authEmailPlaceholder: '邮箱',
    authSendLink: '寄一封入内信',
    authCheckMail: '信已寄出。打开邮件后回到这里。',
    authRequired: '请先入内。卦要知道是谁在问。',
    authError: '入口未开，再试一次。',
    authErrorPrefix: 'Supabase 返回',
    authSignedIn: '已入内',
    authTemporaryAccount: '临时账号',
    authTemporaryHint: '此浏览器会保留你的记录。之后可绑定邮箱，换设备也能找回。',
    authLeave: '离开',
    account: '账号',
    dailyAlreadyCast: '今日已起一卦。\n卦不可频问，问多则散。先守住这一问，明日再来。',
    dailyCheckFailed: '今日之卦暂未验明。稍等再试。',
    testComplete: '测试成卦',
    modePaused: '3D 暂停',
    insightButton: '此卦照见',
    resetButton: '复位',
    observing: '正在观象',
    hexagramComplete: '卦已成',
    expandChanges: '展开十八变',
    collapseChanges: '收起十八变',
    recordsTitle: '记录',
    currentPrefix: '当前',
    linePrefix: '第',
    changePrefix: '变',
    noLineYet: '尚未成爻',
    currentLineInProgress: '爻进行中',
    resultQuestion: '问',
    primaryGua: '本卦',
    changedGua: '之卦',
    movingLines: '变爻',
    sourceTaken: '所取之辞',
    mainText: '主辞',
    supportText: '辅辞',
    originalGua: '本卦',
    transformedGua: '变卦',
    home: '回主页',
    book: '再读旧札',
    historyTitle: '近日记录',
    historyKicker: '此处留存',
    historyEmpty: '这里还没有完成后的解读记录。',
    historyClose: '关闭记录',
    historyNotePlaceholder: '留一条短注记',
    splitChoiceHint: '这一步由你来分，结果来自你的选择。',
    aboutTitle: '关于观天',
    aboutClose: '关闭关于观天',
    shareButton: '分享卦帖',
    shareWriting: '卦象落纸中……',
    sharePosterTitle: '卦帖',
    sharePreviewTitle: '卦帖已成',
    shareSave: '保存 PNG',
    shareSaveHint: '手机端可打开或长按图片保存。',
    supportLine: '如果这一卦对你有所照见，可以留下一杯茶。',
    supportButton: '请一杯茶',
    returnTomorrow: '今日一问至此。明日可再来一卦。',
    onboardingPages: [
      '大衍筮法，\n是《易经》中最古老的起卦方式。',
      '古人认为：\n天地运行，\n会在变化中留下“象”。',
      '五十根蓍草。\n\n一根归天。\n\n余下四十九，\n进入变化。',
      '分而为二。\n\n象天地。\n\n挂一以象三。\n\n揲之以四。',
      '你不是在预测未来，\n你是在看：\n此刻的变化，\n正往哪里去。',
    ],
    yinLine: '阴爻',
    yangLine: '阳爻',
    noMovingLine: '无',
    changingLine: '变爻',
    unchangedLine: '不变',
    status: {
      idle: '请输入所问之事',
      awaitingQuestion: '问题已置于案前',
      reserveOne: '大衍之数五十，其用四十有九',
      chooseSplit: '请选择分草处',
      split: '分而为二',
      takeOne: '右取一，以象三才',
      countLeft: '左堆四四数之',
      countRight: '右堆四四数之',
      changeComplete: '一变已成',
      lineComplete: '三变成一爻',
      hexagramComplete: '卦已成',
      waitingSplitDetail: '点击蓍草束任意位置来分而为二',
    },
    detail: {
      left: '左',
      right: '右',
      takeOne: '右取一',
      leftRemainder: '左余',
      rightRemainder: '右余',
      removed: '去策',
      remaining: '余',
    },
    lineValues: {
      6: '老阴',
      7: '少阳',
      8: '少阴',
      9: '老阳',
    },
  },
} as const

export const COPY = COPY_BY_LANGUAGE.zh
